### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by p0licat** [p0licat/distnet#3]
### main

- [x]   write tests
- [x]   view connections
- [x]   unused variables + warnings, coverage
  - [x] pip coverage, pylint

- [x]      PKG_RESOURACES
- [x]   arguments for script usage

- [x]    replace main.py
  - [x]      __main__.py
  - [x]      script-like

- [x] 	    write log to file command line option / arg
  - [ ]        syntax, csv, ? DB?
  - [ ]        read files?
  - [x]        unique ips
  - [x]        mapper
  - [ ]        session

- [x]    https://docs.python.org/3.5/library/argparse.html https://docs.python.org/3.5/library/optparse.html

- [ ] exceptions restructure
 - [x] inheritance v1
 - [ ] inheritance v2

- [ ]   databases / file output
  - [x]     v1: file output
  - [ ]     v2: output structure
  - [ ]     research: import and export, reading files

- [ ]   virtualenv, pypi, setup.py and packaging
  - [x]     directory structure
  - [x]     setup.py setuptools
    - [x]     syntax
    - [x]     versioning system
    - [x]         pkg_resources
    - [ ]         restructure
    - [ ]     ? tests? pylint?
    - [x]     NS resolve (TcpEntry field?) / ip -> resolved-as
  - [ ]     tox
  - [x]     reading:
    - [x]     https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure
    - [x]     https://docs.pytest.org/en/latest/goodpractices.html#tox
    - [x]     https://packaging.python.org/overview/
    - [x]     https://setuptools.readthedocs.io/en/latest/

- [x]   branch into:
  - [x]     master
  - [x]     develop
  - [x]     visual_map
  - [ ]     text_map (script)

- [x]   pylint:
  - [x] full revision
  - [x] python 3 only
  - [ ] bad exception string passing style

- [x]   coverage
  - [x] running
  - [x] full tests coverage

- [x]     DNS query
  - [x] https://routley.io/tech/2017/12/28/hand-writing-dns-messages.html
  - [x] implemented as socket.gethostbyaddr

- [x]     WHOIS query
  - [x] implemented as python-whois whois.whois()
- [x]     decision tree for map drawing
- [x]     script branching redo and branch for graphical mode
- [ ]     tempfile https://docs.python.org/3.5/library/tempfile.html for a.png

# testing
- [x] test with diferent files
- [ ] renaming

# style
- [ ]   check names and rename

# functionality
- [x] Popen file -> file -E ! (or stat , lstat)

- [ ] Documentation generator i.e. sphinx

# versioning
    https://python-packaging.readthedocs.io/en/latest/non-code-files.html
    https://stackoverflow.com/questions/6028000/how-to-read-a-static-file-from-inside-a-python-package
    http://peak.telecommunity.com/DevCenter/PythonEggs#accessing-package-resources
    [x]   packaging https://medium.com/small-things-about-python/lets-talk-about-python-packaging-6d84b81f1bb5
